---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: naverlandrobot
  namespace: naver
  labels:
    app: naverlandrobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naverlandrobot
  template:
    metadata:
      labels:
        app: naverlandrobot
    spec:
      containers:
        - name: naverlandrobot
          image: ghcr.io/phillipleblanc/naverlandrobot:latest
          imagePullPolicy: Always
          env:
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid-password
                  key: sendgrid-password
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: naverlandrobot
  namespace: naver
spec:
  type: NodePort
  selector:
    app: naverlandrobot
  ports:
    - name: http
      nodePort: 8000
      protocol: TCP
      port: 8000
      targetPort: 8000
