name: build

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

  workflow_dispatch:

jobs:
  node_build:
    name: Build & lint naverlandrobot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          yarn
          yarn build
          yarn lint

  deploy:
    needs: docker_build
    name: Deploy naverlandrobot
    runs-on: self-hosted
    environment: prod

    defaults:
      run:
        working-directory: /home/phillip

    steps:
      - run: sudo docker pull ghcr.io/phillipleblanc/naverlandrobot:latest
      - run: sudo docker rm --force naverland
      - run: sudo docker run --env-file ./naverland.env --name naverland -p 8000:8000 --init --cap-add=SYS_ADMIN --restart=always -d ghcr.io/phillipleblanc/naverlandrobot:latest

  docker_build:
    name: Build naverlandrobot image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: phillipleblanc
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/trunk' }}
          tags: |
            ghcr.io/phillipleblanc/naverlandrobot:latest
            ghcr.io/phillipleblanc/naverlandrobot:0.1.0
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
